namespace NexusForever.WorldServer.Game.Support.Static
{
    public enum BugSubCategory
    {
        World = 1,
        MapMiniMap = 2,
        Props = 3,
        Other = 4,
        SoundEffects = 5,
        Music = 6,
        AudioOther = 7,
        SkillsAndAbilities = 8,
        Animation = 9,
        CharacterOther = 10,
        ArtAnimation = 11,
        Combat = 12,
        TextDialog = 13,
        CreatureOther = 14,
        Vendors = 15,
        ItemsRewards = 16,
        Tradeskills = 17,
        EconomyOther = 18,
        CannotComplete = 19,
        NotOnMapMiniMap = 20,
        QuestText = 21,
        QuestReward = 22,
        QuestOther = 23,
        Performance = 24,
        Connection = 25,
        Crashes = 26,
        TechnicalIssueOther = 27,
        Chat = 28,
        Datachron = 29,
        QuestTracker = 30,
        ActionBar = 31,
        Codex = 32,
        CharacterPanel = 33,
        Inventory = 34,
        Tooltips = 35,
        UIOther = 36,
        DescribeIssue = 37,
        HousingOther = 38
    }
}
